---
title: "Data_cleaning2"
author: "David"
date: "2024-01-24"
output: html_document
---



```{r, include = FALSE}
library(viridis)
library(dplyr)
library(ggplot2)
library(lme4)
library(Matrix)
library(afex)
library(performance)
library(see)
```


```{r, include = FALSE}
###############################################
###  load and extract the new cleaned rds files
###############################################
new_folder_path <- "C:/Users/David/Desktop/SeedFor/Data analysis/SEEDFOR/Data/TOMST_Cleaned1"
#### 1-load ###
# Get a list of all RDS files in the folder
rds_files <- list.files(path = new_folder_path, pattern = "\\.rds$", full.names = TRUE)

# Create an empty list to store loaded data frames
loaded_data_frames <- list()

# Loop through each RDS file and load it into R
for (rds_file in rds_files) {
  loaded_data <- readRDS(rds_file)
  loaded_data_frames[[basename(rds_file)]] <- loaded_data
}

#### 2-extract ###
# Example: Extract the first loaded data frame from the list
first_data_frame <- loaded_data_frames[[1]]
head(first_data_frame)
# Create an empty list to store loaded data frames
loaded_data_frames <- list()

# Loop through each RDS file and load it into R
for (rds_file in rds_files) {
  loaded_data <- readRDS(rds_file)
  loaded_data_frames[[basename(rds_file)]] <- loaded_data
}

# Use list2env to create separate data frames in the R environment
list2env(loaded_data_frames, envir = .GlobalEnv)


#### 3-Combine all loaded data frames into one data frame ###

combined_data <- do.call(rbind, loaded_data_frames)
rownames(combined_data) <- NULL
head(combined_data)



summary(combined_data)
```

# Filtered data from loggers that were out of soil and not working properly
```{r, echo=FALSE}

## The Logger 94200377 on Site 6-O is not working properly so we remove Site 6 from the data
filtered_data <- combined_data %>%
  filter(!(logger_id %in% c("94200377", "94242031", "94242033", "94242034", "94242039", "94242043", "94242047", "94242059")))



# Convert date column to a datetime object
filtered_data$date <- as.POSIXct(filtered_data$date, format="%Y-%m-%d %H:%M:%S")

# Create a new column for the date without the time component
filtered_data$day <- as.Date(filtered_data$date)
head(filtered_data)
```

# Aggregating the data 
## Aggregate the data to daily averages
```{r, echo=FALSE}
daily_averages <- filtered_data %>%
  group_by(day, Canopy_openness, Site) %>%
  summarize(
    avg_T1 = mean(T1),
    avg_T2 = mean(T2),
    avg_T3 = mean(T3),
    avg_soil_moisture = mean(soil_moisture)
    # Add other derivative measures as needed
  )
head(daily_averages)
```

## Group by day, Canopy_openness, and Site and calculate daily min and max temperatures
```{r,echo=FALSE}
daily_extremes <- filtered_data %>%
  group_by(day, Canopy_openness, Site) %>%
  summarize(
    min_T1 = min(T1, na.rm = TRUE),  
    max_T1 = max(T1, na.rm = TRUE),
    min_T2 = min(T2, na.rm = TRUE),  
    max_T2 = max(T2, na.rm = TRUE),
    min_T3 = min(T3, na.rm = TRUE),  
    max_T3 = max(T3, na.rm = TRUE)
  )

head(daily_extremes)
```
